export const SITE_NAME = "Clearpack";
export const SITE_URL = "www.clearpack.com";

export const alarmCode = {
  0: "NO FAULT",
  1: "E-STOP PRESSED",
  2: "DOOR OPEN FrontRight",
  3: "DOOR OPEN FrontLeft",
  4: "DOOR OPEN BackRight",
  5: "DOOR OPEN BackLeft",
  6: "DOOR OPEN RightSide1",
  7: "DOOR OPEN LeftSide1",
  8: "DOOR OPEN FrontCenter",
  9: "DOOR OPEN BackCenter",
  10: "DOOR OPEN RightSide2",
  11: "DOOR OPEN LeftSide2",
  12: "SLIPPED - I/F StarWheel",
  13: "SLIPPED TransferStarWheel",
  14: "SLIPPED OutfeedStarWheel",
  15: "JAMMED-I/F Screw",
  16: "HIGH LIMIT Active AnalogLevel ",
  17: "HIGH LIMIT Active DigitalLevel ",
  18: "LOCK NOT OPENED CapperTurret",
  19: "NOT IN RETRACT POSITN DrainPan",
  20: "AIR PRESSURE LOW",
  21: "VFD FAULT FILLER",
  22: "VFD FAULT I/F Conveyor",
  23: "VFD FAULT CapSorter",
  24: "VFD FAULT  AdditionalCapSorter",
  25: "VFD FAULT CapElevator",
  26: "VFD FAULT CapScrew",
  27: "VFD FAULT CapConveyor",
  28: "OVERLOAD Capper Motor",
  29: "OVERLOAD CapperVaccumMotor",
  30: "OVERLOAD Filler UpDown Motor",
  31: "DOOR OPEN CapSorter",
  32: "UPSTREAM ACC LOW",
  33: "CAP LOW-CapSorter",
  34: "ACC FULL Downstream",
  35: "REJECT ACC JAM",
  36: "REJECT ACC FULL",
  37: "PRODUCT LEVEL LOW",
  38: "LOW Cap Acc",
  39: "HIGH Addition Cap Acc",
  40: "LOW Cap In Cap Elevator",
  41: "PRODUCTION MODE",
  42: "DRAINING MODE",
  43: "CLEANING MODE",
  44: "CHANGE OVER MODE",
  45: "MANUAL MODE",
  46: "NOT READY",
  47: "SYNCHRONISATION IN PROGRESS",
  48: "NOT READY Conveyor",
  49: "NOT READY Product Supply",
  50: "TOO MANY Cap Reject",
  51: "OPERATOP PANEL STOP",
  52: "OPEARATOR PANEL START",
  53: "DOORS OK",
  54: "ALARM 58",
  55: "DRAIN PAN EXTEND During Draining",
  56: "Out",
  57: "DOOR OPEN Add Cap Sorter",
  58: "ACC HIGH Add Cap",
  59: "CAP LOW In Add Cap Sorter",
  60: "AUTO SHUT OFF ALARM1",
  61: "AUTO SHUT OFF ALARM2",
  62: "ZERO PROD CNTR VALUE"
};

export const skuCode = {
  1: "2 LITRE FORTUNE",
  2: "5 LITRE FORTUNE",
  3: "2 LITRE KING",
  4: "5 LITRE KING",
  5: "5 LITRE PET"
};
