export const HANDLE_CHANGE_ITEM = "HANDLE_CHANGE_ITEM";
export const HANDLE_DATE_CHANGE = "HANDLE_DATE_CHANGE";
export const HANDLE_TABLE_VIEW_CHANGE = "HANDLE_TABLE_VIEW_CHANGE";
export const HANDLE_CHART_VIEW_CHANGE = "HANDLE_CHART_VIEW_CHANGE";
export const HANDLE_SUBMIT_COMMENT = "HANDLE_SUBMIT_COMMENT";
export const HANDLE_DAY_CHANGE = "HANDLE_DAY_CHANGE";
export const HANDLE_REQUEST_VIDEO = "HANDLE_REQUEST_VIDEO";
